replicaCount: 5
springProfile: prd

ingress:
  enabled: true
  className: nginx
  host: spring-boot-api.company.com

config:
  json: |
    {
      "service": "spring-boot-api",
      "environment": "prd",
      "features": {
        "api": true,
        "logs": true,
        "soap": true
      }
    }

resources:
  requests:
    cpu: 300m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi
