replicaCount: 3

image:
  repository: busybox
  pullPolicy: IfNotPresent
  tag: stable

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  automount: false
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

springProfile: dev

shutdown:
  url: http://localhost:8080/service/shutdown

config:
  json: |
    {
      "service": "spring-boot-api",
      "environment": "dev",
      "features": {
        "api": true,
        "logs": true,
        "soap": true
      }
    }

service:
  type: ClusterIP
  port: 8080
  ports:
    - name: api
      port: 8080
      targetPort: 8080
      path: /api
    - name: logs
      port: 8081
      targetPort: 8081
      path: /logs
    - name: soap
      port: 8082
      targetPort: 8082
      path: /soap

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: dev.spring-boot-api.local
  tls: []

httpRoute:
  enabled: false
  annotations: {}
  parentRefs:
    - name: gateway
      sectionName: http
  hostnames:
    - chart-example.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /headers

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

probes:
  liveness:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3
  readiness:
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}
