replicaCount: 3
springProfile: dev

ingress:
  enabled: true
  className: nginx
  host: dev.spring-boot-api.dev.company.io

config:
  json: |
    {
      "service": "spring-boot-api",
      "environment": "dev",
      "features": {
        "api": true,
        "logs": true,
        "soap": true
      }
    }

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi
